services:
  master:
    build: .
    hostname: master
    command: ru.nsu.chepenkov.prime.MasterNode
    ports:
      - "8080:8080" # Для клиентов
      - "8081:8081" # Для регистрации воркеров
    networks:
      - prime-net

  worker1:
    build: .
    command: ru.nsu.chepenkov.prime.WorkerNode
    depends_on:
      - master
    networks:
      - prime-net

  worker2:
    build: .
    command: ru.nsu.chepenkov.prime.WorkerNode
    depends_on:
      - master
    networks:
      - prime-net

  client:
    build: .
    command: ru.nsu.chepenkov.prime.PrimeClient
    depends_on:
      - master
    stdin_open: true
    tty: true
    networks:
      - prime-net

networks:
  prime-net:
    driver: bridge
